name = "vieps"
main = "js/vieps-worker.js"
compatibility_date = "2026-09-10"
workers_dev = true

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "jagports"
migrations_dir = "migrations"

[vars]
RANGE_BINDINGS = '{"xk":"RANGE_XK"}'

[[d1_databases]]
binding = "RANGE_XK"
database_name = "parts-xk"
database_id = "55a0ebdb-6a86-4c2a-9ede-d4da2e47db00"
