name = "vieps"
main = "../../../../../base/application-platform/application/jagports/src/index.js"
compatibility_date = "2026-09-10"
workers_dev = true

[assets]
directory = "../../../../../base/application-platform/application/jagports/public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "jagports"
migrations_dir = "../../../../../base/application-platform/application/jagports/migrations"

[env.production]
name = "jagports"
